MODULES:
  - "bblib.environments.RealEnvironment"


save_folder_prefix: "real"
num_episodes: 400

env_config:
  IMPORT: 'exps/default/env_config.yaml'

environmentFactory:
  CLASS: 'RealEnvironmentFactory'
  env_config:
    REF: "env_config"

agent:
  IMPORT: 'exps/default/agent.yaml'


